[package]
name = "pals"
version = "0.1.0"
authors = ["Ivan Ladelshchikov <tsionyx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
base64 = "0.13"
aes = "0.6"
rand = "0.7"
